# Generated by Django 5.0.2 on 2024-02-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('author', models.CharField(max_length=60)),
                ('pdf', models.FileField(upload_to='book/pdf')),
                ('cover', models.ImageField(upload_to='book/cover')),
            ],
        ),
    ]
